version: '3'
services:
  mkdocs:
    image: jssdocente/mkdocs-daw
    build:
      context: ./.docker
      dockerfile: dockerfile
      
    container_name: cctses-integra
    ports:
      - "8010:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true