site_name: CCTSES - Documentación integración
site_url: https://phevositc.github.io/cctses-integra
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "Requerimientos funcionales": "funcional-info.md"
  - "Versión 1.6":
    - "Inicio": "versions/1.6/index.md"
    - "Circuito A":
      - "Técnica": "versions/1.6/CircuitoA/circuitoA-doc.md"
      - "Funcional": "versions/1.6/CircuitoA/CircuitoA-doc_funcional.md"
    - "Circuito B":
      - "Técnica": "versions/1.6/CircuitoB/CCTSES-doc_tecnica.md"
      - "Funcional": "versions/1.6/CircuitoB/CircuitoB-doc_funcional.md"
  - "Versión 1.5":
    - "Inicio": "versions/1.5/index.md"
    - "Circuito A":
      - "Técnica": "versions/1.5/CircuitoA/circuitoA-doc.md"
      - "Funcional": "versions/1.5/CircuitoA/CircuitoA-doc_funcional.md"
    - "Circuito B":
      - "Técnica": "versions/1.5/CircuitoB/CCTSES-doc_tecnica.md"
      - "Funcional": "versions/1.5/CircuitoB/CircuitoB-doc_funcional.md"


theme:
  language: es
  favicon: img/favicon.png
  name: "material"
  palette:
    - scheme: default
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate 
      primary: light blue
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  icon:
    annotation: material/plus-circle
  font:
    text: Roboto
    code: Roboto Mono
  logo: "img/favicon.png"
  features:
    - header.autohide
    # - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - navigation.top
    #- navigation.expand
    - navigation.path
    - content.code.annotate
    - content.tooltips
  custom_width: false

extra:
  search:
    language: "es"
  social:
    - icon: material/email-edit
      link: mailto:<phevositc@gmail.com>
  #analytics:
    #provider: google
    #property: G-X6D0LR7TC8

extra_css:
  - extra/css/extra.css

plugins:
  - search
  - macros
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2025-2026 Phevos IT Consulting S.L
